apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: urlshorteners.operators.sk.com
spec:
  group: operators.sk.com
  versions:
    - name: v1 # it's possible to provide multiple versions of a CRD
      served: true # it's possible to disable a CRD
      storage: true # there can be multiple versions but only one can be used to store the objects
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
  scope: Namespaced # resources can be namespaced or available for the whole cluster
  names:
    plural: urlshorteners
    singular: urlshortener
    kind: UrlShortener # this name is being used in manifests
    shortNames: # these short names can be used in the CLI, e.g. kubectl get er
    - usho
